n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro valor: '))

print('A soma vale {}'.format(n1 + n2))
print('A subtração vale {}'.format(n1 - n2))
print('A multiplicação vale {}'.format(n1 * n2))
print('A divisão vale {}'.format(n1 / n2))
print('A potência vale {}'.format(n1 ** n2))
print('A divisão inteira vale {}'.format(n1 // n2))
print('A resto da divisão vale {}'.format(n1 % n2))
